on: [push]
jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: 'Deploy Nikola to GitHub Pages'
    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        set-safe-directory: '/home/runner/work/hnm-nikola/hnm-nikola'
    - name: look around
      run: |
        pwd
        ls -la
        cat .git/config
        # seems the set-safe-directory above just does nothing. try manually...
        git config --global --add safe.directory /github/workspace
        git config --global --add safe.directory /home/runner/work/hnm-nikola/hnm-nikola
        cat .git/config
    - name: Build and Deploy Nikola
      uses: getnikola/nikola-action@v3
      with:
        dry_run: false

