on: [push]
jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: 'Deploy Nikola to GitHub Pages'
    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        set-safe-directory: '/home/runner/work/hnm-nikola/hnm-nikola'
      run: |
        pwd
        ls -la
        cat .git/config
        ls -la /home/runner/work/hnm-nikola/hnm-nikola
        cat /home/runner/work/hnm-nikola/hnm-nikola/.git/config
    - name: Build and Deploy Nikola
      uses: getnikola/nikola-action@v3
      with:
        dry_run: false

